name: Every2DaysScrape

on:
  schedule:
    - cron: '0 8 */2 * *'  # 8:00 UTC, every 2 days
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create service_account.json
        # Write the secret into a file at runtime
        run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py
